;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-indent-line-or-region
	down-list
	indent-for-tab-command
	org-beginning-of-line
	org-cycle
	org-delete-char
	org-end-of-line
	org-indent-line
	org-indent-region
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	eval-buffer
	recompile
	))
